const cloudinary = require("../config/cloudinary");

/**
 * Upload a file buffer to Cloudinary.
 *
 * Security: All documents are uploaded with:
 *  - type: "authenticated"  — Cloudinary serves them only with a signed URL
 *  - access_mode: "authenticated"
 * This ensures that even if someone obtains a publicId they cannot access
 * the file without a valid signed URL generated by the backend.
 *
 * @param {Buffer} buffer - File buffer from multer memory storage
 * @param {string} originalName - Original filename from the client
 * @param {string} mimeType - MIME type of the file
 * @param {string} [folder] - Cloudinary folder path
 * @returns {Promise<{publicId: string, resourceType: string, format: string, bytes: number}>}
 */
const uploadFile = (buffer, originalName, mimeType, folder = "nanny-applications") => {
  return new Promise((resolve, reject) => {
    const resourceType = mimeType === "application/pdf" ? "raw" : "image";

    const uploadOptions = {
      folder,
      resource_type: resourceType,
      // Authenticated delivery — prevents public access without a signed URL
      type: "authenticated",
      access_mode: "authenticated",
      // Store original filename in the asset metadata (for display only)
      context: { original_name: originalName },
    };

    const uploadStream = cloudinary.uploader.upload_stream(
      uploadOptions,
      (error, result) => {
        if (error) {
          return reject(
            Object.assign(new Error(`Cloudinary upload failed: ${error.message}`), {
              http_code: error.http_code,
            })
          );
        }
        resolve({
          publicId: result.public_id,
          resourceType: result.resource_type,
          format: result.format || "",
          bytes: result.bytes || 0,
        });
      }
    );

    // Write the buffer into the upload stream
    const { Readable } = require("stream");
    const readable = new Readable();
    readable.push(buffer);
    readable.push(null);
    readable.pipe(uploadStream);
  });
};

/**
 * Delete a file from Cloudinary by its publicId.
 * Requires the resource_type so Cloudinary knows which asset type to delete.
 *
 * @param {string} publicId
 * @param {string} [resourceType] - "image" | "raw" | "video"
 * @returns {Promise<void>}
 */
const deleteFile = async (publicId, resourceType = "raw") => {
  const result = await cloudinary.uploader.destroy(publicId, {
    resource_type: resourceType,
    type: "authenticated",
    invalidate: true,
  });

  if (result.result !== "ok" && result.result !== "not found") {
    throw new Error(`Cloudinary deletion failed for '${publicId}': ${result.result}`);
  }
};

/**
 * Generate a short-lived signed URL for an authenticated Cloudinary asset.
 * This is what admins use to view documents — never expose raw publicIds to
 * the public frontend.
 *
 * @param {string} publicId
 * @param {string} [resourceType]
 * @param {number} [expiresInSeconds] - Default: 1 hour
 * @returns {string} Signed URL
 */
const generateSignedUrl = (publicId, resourceType = "raw", expiresInSeconds = 3600) => {
  const expireAt = Math.floor(Date.now() / 1000) + expiresInSeconds;

  return cloudinary.utils.private_download_url(publicId, "", {
    resource_type: resourceType,
    type: "authenticated",
    expires_at: expireAt,
  });
};

module.exports = { uploadFile, deleteFile, generateSignedUrl };
